extends:
   - 'airbnb-base'
env:
   node: true
   browser: true
rules:
   max-len: ["error", { "code": 80 }]
   func-names: ["error", "never"]
   import/extensions: [<severity>, "never"]
   no-param-reassign: ["error", { "props": false }]
